### ISSUE TITLE
Wrong namespace in itsrdf

### ISSUE THREAD

**Issue by skarampatakis** [semantic-web-company/nif#1]
Namespace for itsrdf has been set wrong [here](https://github.com/semantic-web-company/nif/blob/edbfdc4544b78eac6bd2d00bfe85ddb2de70acb8/nif/annotation.py#L39
) and on some tests. Please consider change this to ```http://www.w3.org/2005/11/its/rdf#```.

**Comment by artreven** [comment]
Modified in 51c955cae150688724ef93d35767694d316010b6
